services:
  - type: web
    name: freelancer-backend
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: PORT
        value: 10000
      - key: CORS_ORIGIN
        value: https://freelancer-app-chi.vercel.app
      - key: API_URL
        value: https://freelancer-app-chi.vercel.app/api
    headers:
      - path: /*
        name: Access-Control-Allow-Origin
        value: https://freelancer-app-chi.vercel.app
      - path: /*
        name: Access-Control-Allow-Methods
        value: GET, POST, PUT, DELETE, OPTIONS, PATCH
      - path: /*
        name: Access-Control-Allow-Headers
        value: X-Requested-With, Content-Type, Authorization
    healthCheckPath: /health
    autoDeploy: true
    plan: free
    disk:
      name: data
      mountPath: /data
      sizeGB: 1 